# pyproject.toml for csv-inv-order

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "csv-inv-order"
version = "0.0.2"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11.2"
dependencies = ["csv-app", "tui-app"]

[project.urls]
repository = "https://github.com/dangyogi/csv-inv-order.git"

[project.scripts]
inv-order-rows = "csv_inv_order.rows:run"
inv-order-tables = "csv_inv_order.tables:run"
recalibrate = "csv_inv_order.recalibrate:run"
inv-order = "csv_inv_order.tui:run"

[tool.setuptools.package-dir]
csv_inv_order = "csv_inv_order"

[tool.pytest.ini_options]
testpaths = ["tests"]
