# database.py

# Do not edit!  This is machine generated by running "python rows.py".

if not __package__:
    __package__ = 'csv_inv_order'

from .tables import *


Months = Tables['Months']

Inv_checklist = Tables['Inv_checklist']

Orders = Tables['Orders']

Items = Tables['Items']

Products = Tables['Products']

Inventory = Tables['Inventory']

Month_stats = Tables['Month_stats']

Order_stats = Tables['Order_stats']

Steps = Tables['Steps']

