# database.py

# Do not edit!  This is machine generated by running "python rows.py".

if not __package__:
    __package__ = 'csv_inv_order'

from .tables import *


Items = Tables['Items']

Products = Tables['Products']

Inventory = Tables['Inventory']

Orders = Tables['Orders']

Months = Tables['Months']

